# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19c95a48938adab274fbf14f07b5645dd0f611e13cc4c29bae47276c66db9a774d12cf108276d0827af82c5f1111ee210537cca8ee49836ee0f4e1bbb2a1428f

test:
  secret_key_base: 0b8ccce63f4f606a09ff995ec4c0a54202be5db6830212b4a196221e80e8c278c918062bec0df815d72e3fb3e7297fdf64c4c83a0f9742560ecf7baa08978529

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
